name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'

env:
  GO_VERSION: 1.19

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=10
        ports:
            - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: todo
          MYSQL_PASSWORD: todo
          MYSQL_DATABASE: todo
      redis:
        image: redis
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 6379:6379
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v3
      - run: |
          go install github.com/k0kubun/sqldef/cmd/mysqldef@latest
          mysqldef -u todo -p todo -h localhost -P 3306 todo < ./_tools/mysql/schema.sql

      - name: Build
        run: go build -v ./...

      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: report coverage
        uses: k1Low/octocov-action@v0